FROM node:18.15-alpine as base
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:18.15-alpine as production
WORKDIR /app
COPY package*.json ./
RUN npm install 
USER node
COPY --from=base --chown=node:node /usr/src/app/dist ./dist 
COPY --chown=node:node ./server/server.mjs ./server/server.mjs
COPY --chown=node:node ./server/winston.mjs ./server/winston.mjs
EXPOSE 3000
CMD [ "node", "server/server.mjs" ]
