FROM node:18.15-alpine as base
WORKDIR /usr/src/app
COPY package*.json ./

FROM base as dev
RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && \
    npm install
COPY . .
CMD [ "npx", "astro", "dev", "--host" ]
